spotTerminationexporter:
  image:
    repository: "banzaicloud/spot-termination-exporter"
    tag: "0.0.1"
    imagePullPolicy: IfNotPresent
  replicas: 1
  service:
    type: ClusterIP
  logLevel: "debug"
  bindAddr: 9189
  hostPort: 9189
  metadataEndpoint: "http://169.254.169.254/latest/meta-data/"
  metricsPath: "/metrics"
resources:
  requests:
    memory: 256Mi
    cpu: 120m

nodeSelector:
  "lifecycle": "EC2Spot"

tolerations: []

affinity: {}

securityContext: {}