loki:
  enabled: true
  service:
    type: ClusterIP
    nodePort:
    port: 3100
    annotations: {}
    labels: {}

promtail:
  enabled: true

fluent-bit:
  enabled: false

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: true
  image:
    tag: 6.7.0

prometheus:
  enabled: false

